<?php

declare(strict_types=1);

namespace GracjanKubicki\ArchitectureKit\Resources;

final class GeneratedResourceMarker
{
    public const PREFIX = '<!-- Generated by Laravel Architecture Kit. Do not edit manually.';

    public static function top(string $contents): string
    {
        $hash = hash('sha256', $contents);

        return self::PREFIX." hash=sha256:{$hash} -->\n\n".trim($contents)."\n";
    }

    public static function skill(string $contents): string
    {
        $contents = trim($contents);
        $hash = hash('sha256', $contents);
        $marker = self::PREFIX." hash=sha256:{$hash} -->";

        if (! str_starts_with($contents, "---\n")) {
            return $marker."\n\n".$contents."\n";
        }

        $end = strpos($contents, "\n---", 4);

        if ($end === false) {
            return $marker."\n\n".$contents."\n";
        }

        $frontmatterEnd = $end + 4;

        return substr($contents, 0, $frontmatterEnd)."\n\n{$marker}\n\n".ltrim(substr($contents, $frontmatterEnd))."\n";
    }
}
