<?php

declare(strict_types=1);

namespace Taqie\ArchitectureKit\Support;

use Illuminate\Filesystem\Filesystem;
use RuntimeException;
use Taqie\ArchitectureKit\Architecture;

final class ArchitectureResources
{
    public const MARKER_PREFIX = '<!-- Generated by Laravel Architecture Kit. Do not edit manually.';

    public function __construct(
        private readonly string $packagePath,
        private readonly string $projectPath,
        private readonly Filesystem $files = new Filesystem(),
    ) {
    }

    /**
     * @param  array<int, Architecture>  $enabled
     */
    public function guideline(array $enabled): GeneratedFile
    {
        $body = implode("\n\n", [
            '## Architecture Kit',
            $this->globalRules(),
            $this->packageFirstRule(),
            $this->testabilityRule(),
            $this->enabledArchitectures($enabled),
            $this->composition($enabled),
            $this->architectureRules($enabled),
        ]);

        $contents = $this->withTopMarker($body);

        return new GeneratedFile(
            path: $this->projectPath.'/.ai/guidelines/architecture-kit.md',
            contents: $contents,
        );
    }

    /**
     * @param  array<int, Architecture>  $enabled
     * @return array<string, GeneratedFile>
     */
    public function skills(array $enabled): array
    {
        $skills = [];

        foreach ($this->ordered($enabled) as $architecture) {
            $contents = $this->files->get($this->skillSource($architecture));
            $this->assertSkillName($architecture, $contents);

            $skills[$architecture->value] = new GeneratedFile(
                path: $this->projectPath.'/.ai/skills/'.$architecture->skillName().'/SKILL.md',
                contents: $this->withSkillMarker($contents),
            );
        }

        return $skills;
    }

    /**
     * @param  array<int, Architecture>  $enabled
     * @return array<int, Architecture>
     */
    public function ordered(array $enabled): array
    {
        return array_values(array_filter(
            Architecture::guidelineOrder(),
            fn (Architecture $architecture): bool => in_array($architecture, $enabled, true),
        ));
    }

    public function guidelineSource(Architecture $architecture): string
    {
        return $this->packagePath.'/resources/architectures/'.$architecture->value.'/guideline.md';
    }

    public function skillSource(Architecture $architecture): string
    {
        return $this->packagePath.'/resources/architectures/'.$architecture->value.'/SKILL.md';
    }

    /**
     * @param  array<int, Architecture>  $enabled
     */
    public function assertSourcesExist(array $enabled): void
    {
        foreach ($enabled as $architecture) {
            foreach ([$this->guidelineSource($architecture), $this->skillSource($architecture)] as $path) {
                if (! $this->files->exists($path)) {
                    throw new RuntimeException("Missing Architecture Kit source resource: {$path}");
                }
            }
        }
    }

    /**
     * @return array<string, string>
     */
    public function existingGeneratedSkillPaths(): array
    {
        $basePath = $this->projectPath.'/.ai/skills';

        if (! $this->files->isDirectory($basePath)) {
            return [];
        }

        $paths = [];

        foreach ($this->files->directories($basePath) as $directory) {
            $name = basename($directory);

            if (! str_starts_with($name, 'architecture-kit-')) {
                continue;
            }

            $skillPath = $directory.'/SKILL.md';

            if ($this->files->exists($skillPath) && $this->isGenerated($skillPath)) {
                $paths[$name] = $skillPath;
            }
        }

        return $paths;
    }

    public function isGenerated(string $path): bool
    {
        return $this->files->exists($path)
            && str_contains($this->files->get($path), self::MARKER_PREFIX);
    }

    /**
     * @param  array<int, Architecture>  $enabled
     */
    private function architectureRules(array $enabled): string
    {
        $sections = ['## Architecture Rules'];

        foreach ($this->ordered($enabled) as $architecture) {
            $guideline = trim($this->files->get($this->guidelineSource($architecture)));

            $sections[] = implode("\n\n", [
                '### '.$architecture->label(),
                'Status: enabled globally.',
                'Skill: `'.$architecture->skillName().'`',
                $guideline,
            ]);
        }

        return implode("\n\n", $sections);
    }

    private function globalRules(): string
    {
        return <<<'MARKDOWN'
This project MUST follow the enabled Architecture Kit patterns globally.

Before changing application architecture:

- Follow the enabled architecture sections in this file.
- Do not introduce architecture patterns that are not listed here.
- Follow existing project structure when it is more specific than the default paths below.
- Keep framework adapters thin and keep business decisions in the architecture boundary selected for that behavior.
- Load the listed Architecture Kit skill before implementing or refactoring code for that architecture.
- Before finishing a code change, run `php artisan architecture-kit:guard --changed --strict`.
- In CI or after committing, run `php artisan architecture-kit:guard --changed --base=origin/main --strict`.
- You MUST fix all Architecture Kit guard errors before final response.
- Do not claim the work is done while the guard reports errors.

Architecture folder purity:

- Architecture folders MUST stay type-pure.
- Do not place supporting classes inside another architecture folder.
- `app/Actions/**` contains Actions only.
- `app/Data/**` contains Data Objects, DTOs, and Result objects only.
- `app/ValueObjects/**` contains Value Objects only.
- `app/Enums/**` contains Enums only.
- `app/Queries/**` contains Query Objects only.
- `app/Http/Resources/**` contains API Resources and Resource Collections only.
- `app/Exceptions/**` contains Exceptions only.
- If the project uses domain-first structure, keep the same purity under the domain folder, for example `app/Documents/Actions`, `app/Documents/Data`, `app/Documents/Enums`, and `app/Documents/Exceptions`.
MARKDOWN;
    }

    private function testabilityRule(): string
    {
        return <<<'MARKDOWN'
## Testability Architecture Rule

Architecture Kit code MUST keep dependencies explicit and testable.

- Do not replace `app(SomeClass::class)` with private static factory helpers that return `new SomeClass()`.
- Do not hide collaborators behind `private static function collaborator(): Collaborator`.
- Prefer constructor injection, method injection, or an enabled architecture boundary such as an Action or Query Object.
- If object creation is real domain construction, keep it local and obvious. If it is a service/collaborator dependency, inject it.
- Code should be easy to test by passing test doubles or focused inputs without reaching into the service container or hidden factories.

Bad replacement:

```php
private static function documentTemplate(): ResolveWorkingCaseDocumentTemplate
{
    return new ResolveWorkingCaseDocumentTemplate();
}
```

Better:

```php
public function __construct(
    private ResolveWorkingCaseDocumentTemplate $documentTemplate,
) {
}
```
MARKDOWN;
    }

    private function packageFirstRule(): string
    {
        return <<<'MARKDOWN'
## Package-First Architecture Rule

AI agents MUST NOT implement custom infrastructure before checking existing options.

Before writing new infrastructure, integrations, parsers, validators, clients, workflow engines, importers, exporters, or reusable technical abstractions:

1. Search for an existing Laravel feature that already solves the problem.
2. Search for maintained Laravel ecosystem packages.
3. Search for maintained third-party PHP packages.
4. Prefer the existing feature or package when it fits the project constraints.
5. Implement custom code only when no suitable package exists, the package is not maintained, it does not fit the project constraints, or it cannot safely provide the required behavior.
6. When custom code is chosen, state the reason in the handoff or implementation notes.

This rule does not replace the enabled architecture rules. Any package integration or custom implementation must still follow the enabled Architecture Kit patterns.
MARKDOWN;
    }

    /**
     * @param  array<int, Architecture>  $enabled
     */
    private function enabledArchitectures(array $enabled): string
    {
        $lines = ['## Enabled Architectures'];

        foreach ($this->ordered($enabled) as $architecture) {
            $lines[] = '- '.$architecture->label().' (`'.$architecture->skillName().'`)';
        }

        return implode("\n", $lines);
    }

    /**
     * @param  array<int, Architecture>  $enabled
     */
    private function composition(array $enabled): string
    {
        $enabledValues = array_map(
            fn (Architecture $architecture): string => $architecture->value,
            $enabled,
        );

        $writeFlow = $this->flow([
            Architecture::ThinControllers->value => 'Route -> Controller',
            Architecture::FormRequests->value => 'FormRequest',
            Architecture::DataObjects->value => 'Data Object',
            Architecture::Actions->value => 'Action',
            Architecture::ValueObjects->value => 'Eloquent/Value Objects',
            Architecture::ApiResources->value => 'API Resource',
        ], $enabledValues);

        $readFlow = $this->flow([
            Architecture::ThinControllers->value => 'Route -> Controller',
            Architecture::FormRequests->value => 'FormRequest/Search Data',
            Architecture::DataObjects->value => 'Data Object',
            Architecture::QueryObjects->value => 'Query Object',
            Architecture::CustomEloquentBuilders->value => 'Custom Eloquent Builder',
            Architecture::ApiResources->value => 'API Resource',
        ], $enabledValues);

        return implode("\n\n", [
            '## How These Architectures Compose',
            'Write flow: '.$writeFlow,
            'Read flow: '.$readFlow,
            'Only use a step when the corresponding architecture is enabled and the endpoint needs that responsibility.',
        ]);
    }

    /**
     * @param  array<string, string>  $steps
     * @param  array<int, string>  $enabled
     */
    private function flow(array $steps, array $enabled): string
    {
        return implode(' -> ', array_values(array_filter(
            $steps,
            fn (string $key): bool => in_array($key, $enabled, true),
            ARRAY_FILTER_USE_KEY,
        )));
    }

    private function withTopMarker(string $contents): string
    {
        $hash = hash('sha256', $contents);

        return self::MARKER_PREFIX." hash=sha256:{$hash} -->\n\n".trim($contents)."\n";
    }

    private function withSkillMarker(string $contents): string
    {
        $contents = trim($contents);
        $hash = hash('sha256', $contents);
        $marker = self::MARKER_PREFIX." hash=sha256:{$hash} -->";

        if (! str_starts_with($contents, "---\n")) {
            return $marker."\n\n".$contents."\n";
        }

        $end = strpos($contents, "\n---", 4);

        if ($end === false) {
            return $marker."\n\n".$contents."\n";
        }

        $frontmatterEnd = $end + 4;

        return substr($contents, 0, $frontmatterEnd)."\n\n{$marker}\n\n".ltrim(substr($contents, $frontmatterEnd))."\n";
    }

    private function assertSkillName(Architecture $architecture, string $contents): void
    {
        if (! str_contains($contents, 'name: '.$architecture->skillName())) {
            throw new RuntimeException("Skill for [{$architecture->value}] must be named [{$architecture->skillName()}].");
        }
    }
}
