<?php

declare(strict_types=1);

namespace Taqie\ArchitectureKit\Support;

use Illuminate\Filesystem\Filesystem;

final readonly class HookResources
{
    public const MARKER = 'Generated by Laravel Architecture Kit. Do not edit manually.';

    public function __construct(
        private string $projectPath,
        private Filesystem $files = new Filesystem,
    ) {}

    /**
     * @param  array<int, string>  $agents
     * @return array<string, GeneratedFile>
     */
    public function files(array $agents): array
    {
        $files = [
            'guard' => new GeneratedFile(
                path: $this->projectPath.'/.architecture-kit/hooks/guard.sh',
                contents: $this->guardScript(),
            ),
            'readme' => new GeneratedFile(
                path: $this->projectPath.'/.architecture-kit/hooks/README.md',
                contents: $this->readme(),
            ),
        ];

        if (in_array('codex', $agents, true)) {
            $files['codex'] = new GeneratedFile(
                path: $this->projectPath.'/.codex/hooks.json',
                contents: $this->codexHooks(),
            );
        }

        if (in_array('claude', $agents, true)) {
            $files['claude'] = new GeneratedFile(
                path: $this->projectPath.'/.claude/settings.json',
                contents: $this->claudeSettings(),
            );
        }

        return $files;
    }

    public function isGenerated(string $path): bool
    {
        return $this->files->exists($path)
            && str_contains($this->files->get($path), self::MARKER);
    }

    private function guardScript(): string
    {
        return <<<'SH'
#!/usr/bin/env bash
# Generated by Laravel Architecture Kit. Do not edit manually.
set -u

MODE="${1:-codex}"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

cd "$ROOT" || exit 1

OUTPUT="$(php artisan architecture-kit:guard --changed --strict --json 2>&1)"
STATUS=$?

if [ "$STATUS" -eq 0 ]; then
    exit 0
fi

printf '%s\n' "$OUTPUT" >&2

if [ "$MODE" = "claude" ]; then
    exit 2
fi

exit "$STATUS"
SH;
    }

    private function readme(): string
    {
        return <<<'MARKDOWN'
<!-- Generated by Laravel Architecture Kit. Do not edit manually. -->

# Architecture Kit Hooks

These hooks run:

```bash
php artisan architecture-kit:guard --changed --strict --json
```

The fix for stale generated Architecture Kit resources is:

```bash
php artisan architecture-kit:install
```

Do not edit generated hook files manually. Re-run:

```bash
php artisan architecture-kit:install-hooks
```
MARKDOWN;
    }

    private function codexHooks(): string
    {
        return $this->json([
            '_architectureKit' => self::MARKER,
            'hooks' => [
                'Stop' => [
                    [
                        'hooks' => [
                            [
                                'type' => 'command',
                                'command' => 'sh "$(git rev-parse --show-toplevel)/.architecture-kit/hooks/guard.sh" codex',
                                'timeout' => 120,
                                'statusMessage' => 'Running Architecture Kit guard',
                            ],
                        ],
                    ],
                ],
            ],
        ]);
    }

    private function claudeSettings(): string
    {
        return $this->json([
            '_architectureKit' => self::MARKER,
            'hooks' => [
                'Stop' => [
                    [
                        'hooks' => [
                            [
                                'type' => 'command',
                                'command' => '${CLAUDE_PROJECT_DIR}/.architecture-kit/hooks/guard.sh claude',
                                'timeout' => 120,
                            ],
                        ],
                    ],
                ],
            ],
        ]);
    }

    /**
     * @param  array<string, mixed>  $payload
     */
    private function json(array $payload): string
    {
        return (json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?: '{}')."\n";
    }
}
