<?php

declare(strict_types=1);

namespace GracjanKubicki\ArchitectureKit\Tests\Feature;

use GracjanKubicki\ArchitectureKit\Install\Hooks\HookWriter;
use GracjanKubicki\ArchitectureKit\Install\RuntimeResolver;
use GracjanKubicki\ArchitectureKit\Tests\TestCase;
use Illuminate\Filesystem\Filesystem;
use Symfony\Component\Process\Process;

class AgentHookIntegrationTest extends TestCase
{
    public function test_it_exposes_one_agent_installation_command(): void
    {
        $this->artisan('list')
            ->expectsOutputToContain('architecture-kit:install-agents')
            ->doesntExpectOutputToContain('architecture-kit:install-hooks')
            ->assertExitCode(0);
    }

    public function test_it_generates_codex_and_claude_hooks(): void
    {
        $this->artisan('architecture-kit:install-agents --codex --claude --hooks')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $files = new Filesystem;

        $guard = $files->get($this->tempPath.'/.architecture-kit/hooks/guard.sh');
        $codex = $files->get($this->tempPath.'/.codex/hooks.json');
        $claude = $files->get($this->tempPath.'/.claude/settings.json');

        $this->assertStringContainsString('Generated by Laravel Architecture Kit', $guard);
        $this->assertStringContainsString('architecture-kit:guard --changed --strict --json', $guard);
        $this->assertStringContainsString('"Stop"', $codex);
        $this->assertStringContainsString('.architecture-kit/hooks/guard.sh', $codex);
        $this->assertStringNotContainsString('_architectureKit', $codex);
        $this->assertStringContainsString('"Stop"', $claude);
        $this->assertStringContainsString('.architecture-kit/hooks/guard.sh claude', $claude);
        $this->assertStringNotContainsString('_architectureKit', $claude);
        $this->assertSame('755', substr(sprintf('%o', fileperms($this->tempPath.'/.architecture-kit/hooks/guard.sh')), -3));
    }

    public function test_it_is_idempotent_for_generated_hooks(): void
    {
        $this->artisan('architecture-kit:install-agents --codex --hooks')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $this->artisan('architecture-kit:install-agents --codex --hooks')
            ->expectsOutputToContain('No agent integration changes needed.')
            ->assertExitCode(0);
    }

    public function test_it_blocks_unmanaged_hook_config(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/.codex');
        $files->put($this->tempPath.'/.codex/hooks.json', '{not json');

        $this->artisan('architecture-kit:install-agents --codex --hooks')
            ->expectsOutputToContain('blocked  .codex/hooks.json')
            ->assertExitCode(1);

        $this->assertSame('{not json', $files->get($this->tempPath.'/.codex/hooks.json'));
    }

    public function test_it_merges_existing_hook_config(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/.codex');
        $files->put($this->tempPath.'/.codex/hooks.json', json_encode([
            'hooks' => [
                'Stop' => [
                    [
                        'hooks' => [
                            [
                                'type' => 'command',
                                'command' => 'vendor/bin/phpunit',
                            ],
                        ],
                    ],
                ],
            ],
        ], JSON_PRETTY_PRINT));

        $this->artisan('architecture-kit:install-agents --codex --hooks')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $contents = $files->get($this->tempPath.'/.codex/hooks.json');

        $this->assertStringContainsString('vendor/bin/phpunit', $contents);
        $this->assertStringContainsString('.architecture-kit/hooks/guard.sh', $contents);
    }

    public function test_it_repairs_old_generated_codex_metadata_field(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/.codex');
        $files->put($this->tempPath.'/.codex/hooks.json', json_encode([
            'hooks' => [
                'Stop' => [
                    [
                        'hooks' => [
                            [
                                'type' => 'command',
                                'command' => 'sh "$(git rev-parse --show-toplevel)/.architecture-kit/hooks/guard.sh" codex',
                                'statusMessage' => 'Generated by Laravel Architecture Kit. Do not edit manually.',
                            ],
                        ],
                    ],
                ],
            ],
            '_architectureKit' => [
                'generated' => true,
            ],
        ], JSON_PRETTY_PRINT));

        $this->artisan('architecture-kit:install-agents --codex --hooks')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $contents = $files->get($this->tempPath.'/.codex/hooks.json');

        $this->assertStringContainsString('"hooks"', $contents);
        $this->assertStringNotContainsString('_architectureKit', $contents);
    }

    public function test_generated_hook_allows_a_valid_gate_and_fails_closed_when_runtime_is_unavailable(): void
    {
        $files = new Filesystem;
        $runner = $this->tempPath.'/fake-runtime.sh';
        $files->put($runner, <<<'SH'
#!/usr/bin/env sh
if [ "${ARCHITECTURE_KIT_FAKE_FAILURE:-0}" = "1" ]; then
    exit 9
fi

printf '%s\n' '{"ok":true}'
SH);
        $files->chmod($runner, 0755);

        (new HookWriter(
            $files,
            $this->tempPath,
            new RuntimeResolver(['driver' => 'custom', 'command' => [$runner]]),
        ))->write([]);

        $hook = new Process([$this->tempPath.'/.architecture-kit/hooks/guard.sh', 'codex'], $this->tempPath);
        $hook->run();

        $this->assertSame(0, $hook->getExitCode());

        $failedHook = new Process([$this->tempPath.'/.architecture-kit/hooks/guard.sh', 'codex'], $this->tempPath, [
            'ARCHITECTURE_KIT_FAKE_FAILURE' => '1',
        ]);
        $failedHook->run();

        $this->assertSame(9, $failedHook->getExitCode());
        $this->assertStringContainsString('runtime unavailable', $failedHook->getErrorOutput());
    }
}
