<?php

declare(strict_types=1);

namespace Taqie\ArchitectureKit\Tests\Feature;

use Illuminate\Filesystem\Filesystem;
use Taqie\ArchitectureKit\Architecture;
use Taqie\ArchitectureKit\Support\ArchitectureConfig;
use Taqie\ArchitectureKit\Support\ArchitectureResources;
use Taqie\ArchitectureKit\Tests\TestCase;

class DoctorCommandTest extends TestCase
{
    public function test_it_passes_when_generated_resources_are_current(): void
    {
        $this->writeCurrentResources([Architecture::Actions]);

        $this->artisan('architecture-kit:doctor')
            ->expectsOutputToContain('current  config/architectures.php')
            ->expectsOutputToContain('current  .ai/guidelines/architecture-kit.md')
            ->assertExitCode(0);
    }

    public function test_it_fails_when_generated_guideline_is_missing(): void
    {
        $config = new ArchitectureConfig($this->tempPath.'/config/architectures.php');
        $config->write([Architecture::Actions]);

        $this->artisan('architecture-kit:doctor')
            ->expectsOutputToContain('missing  .ai/guidelines/architecture-kit.md')
            ->assertExitCode(1);
    }

    public function test_it_fails_when_generated_skill_is_missing(): void
    {
        $files = new Filesystem();
        $config = new ArchitectureConfig($this->tempPath.'/config/architectures.php', $files);
        $resources = new ArchitectureResources(dirname(__DIR__, 2), $this->tempPath, $files);

        $config->write([Architecture::Actions]);

        $guideline = $resources->guideline([Architecture::Actions]);
        $files->ensureDirectoryExists(dirname($guideline->path));
        $files->put($guideline->path, $guideline->contents);

        $this->artisan('architecture-kit:doctor')
            ->expectsOutputToContain('missing  .ai/skills/architecture-kit-actions/SKILL.md')
            ->assertExitCode(1);
    }

    public function test_it_fails_when_generated_skill_is_outdated(): void
    {
        $this->writeCurrentResources([Architecture::Actions]);

        (new Filesystem())->append($this->tempPath.'/.ai/skills/architecture-kit-actions/SKILL.md', "\nmanual edit\n");

        $this->artisan('architecture-kit:doctor')
            ->expectsOutputToContain('outdated .ai/skills/architecture-kit-actions/SKILL.md')
            ->assertExitCode(1);
    }

    public function test_it_fails_when_generated_skill_is_stale(): void
    {
        $this->writeCurrentResources([Architecture::Actions]);

        $files = new Filesystem();
        $files->ensureDirectoryExists($this->tempPath.'/.ai/skills/architecture-kit-value-objects');
        $files->put(
            $this->tempPath.'/.ai/skills/architecture-kit-value-objects/SKILL.md',
            "---\nname: architecture-kit-value-objects\n---\n\n<!-- Generated by Laravel Architecture Kit. Do not edit manually. hash=sha256:old -->\n",
        );

        $this->artisan('architecture-kit:doctor')
            ->expectsOutputToContain('stale    .ai/skills/architecture-kit-value-objects')
            ->assertExitCode(1);
    }

    public function test_it_fails_when_config_uses_raw_strings(): void
    {
        $files = new Filesystem();
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', "<?php\n\nreturn ['enabled' => ['actions']];\n");

        $this->artisan('architecture-kit:doctor')
            ->expectsOutputToContain('blocked  config/architectures.php')
            ->assertExitCode(1);
    }

    public function test_it_fails_when_modern_php_85_is_enabled_without_php_85_requirement(): void
    {
        $this->writeCurrentResources([Architecture::ModernPhp85]);

        $this->artisan('architecture-kit:doctor')
            ->expectsOutputToContain('blocked  composer.json')
            ->expectsOutputToContain('Modern PHP 8.5 is enabled but composer.json does not require PHP 8.5 or newer.')
            ->assertExitCode(1);
    }

    public function test_it_passes_for_modern_php_85_when_project_requires_php_85(): void
    {
        (new Filesystem())->put($this->tempPath.'/composer.json', json_encode([
            'require' => [
                'php' => '^8.5',
            ],
        ], JSON_PRETTY_PRINT));

        $this->writeCurrentResources([Architecture::ModernPhp85]);

        $this->artisan('architecture-kit:doctor')
            ->expectsOutputToContain('current  config/architectures.php')
            ->assertExitCode(0);
    }

    public function test_every_architecture_has_source_resources(): void
    {
        $resources = new ArchitectureResources(dirname(__DIR__, 2), $this->tempPath);

        foreach (Architecture::cases() as $architecture) {
            $this->assertFileExists($resources->guidelineSource($architecture));
            $this->assertFileExists($resources->skillSource($architecture));
        }
    }

    /**
     * @param  array<int, Architecture>  $enabled
     */
    private function writeCurrentResources(array $enabled): void
    {
        $files = new Filesystem();
        $config = new ArchitectureConfig($this->tempPath.'/config/architectures.php', $files);
        $resources = new ArchitectureResources(dirname(__DIR__, 2), $this->tempPath, $files);

        $config->write($enabled);

        $generated = array_merge(
            [$resources->guideline($enabled)],
            array_values($resources->skills($enabled)),
        );

        foreach ($generated as $file) {
            $files->ensureDirectoryExists(dirname($file->path));
            $files->put($file->path, $file->contents);
        }
    }
}
