<?php

declare(strict_types=1);

namespace Taqie\ArchitectureKit\Tests\Feature;

use Illuminate\Filesystem\Filesystem;
use RuntimeException;
use Taqie\ArchitectureKit\Architecture;
use Taqie\ArchitectureKit\Support\ArchitectureConfig;
use Taqie\ArchitectureKit\Support\ArchitectureDoctor;
use Taqie\ArchitectureKit\Support\ArchitectureResources;
use Taqie\ArchitectureKit\Support\GeneratedFile;
use Taqie\ArchitectureKit\Tests\TestCase;

class InstallCommandTest extends TestCase
{
    public function test_it_generates_config_guideline_and_selected_skills(): void
    {
        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', [
                'thin-controllers',
                'form-requests',
                'actions',
                'data-objects',
                'api-resources',
                'laravel-best-practices',
            ], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $files = new Filesystem;

        $config = $files->get($this->tempPath.'/config/architectures.php');
        $guideline = $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md');
        $skill = $files->get($this->tempPath.'/.ai/skills/architecture-kit-actions/SKILL.md');
        $formRequestSkill = $files->get($this->tempPath.'/.ai/skills/architecture-kit-form-requests/SKILL.md');
        $laravelBestPracticesSkill = $files->get($this->tempPath.'/.ai/skills/architecture-kit-laravel-best-practices/SKILL.md');

        $this->assertStringContainsString('Architecture::ThinControllers', $config);
        $this->assertStringContainsString('Architecture::Actions', $config);
        $this->assertStringContainsString('Architecture::LaravelBestPractices', $config);
        $this->assertStringContainsString("'runtime' => [", $config);
        $this->assertStringContainsString("'driver' => 'local'", $config);
        $this->assertStringContainsString('Generated by Laravel Architecture Kit', $guideline);
        $this->assertStringContainsString('### Actions', $guideline);
        $this->assertStringContainsString('### Laravel Best Practices', $guideline);
        $this->assertGreaterThan(
            strpos($guideline, '### API Resources'),
            strpos($guideline, '### Laravel Best Practices'),
        );
        $this->assertStringContainsString('Write flow:', $guideline);
        $this->assertStringContainsString('php artisan architecture-kit:guard --changed --strict', $guideline);
        $this->assertStringContainsString('## Package-First Architecture Rule', $guideline);
        $this->assertStringContainsString('AI agents MUST NOT implement custom infrastructure before checking existing options.', $guideline);
        $this->assertStringContainsString('Search for maintained Laravel ecosystem packages.', $guideline);
        $this->assertStringContainsString('When custom code is chosen, state the reason in the handoff or implementation notes.', $guideline);
        $this->assertStringContainsString('## Testability Architecture Rule', $guideline);
        $this->assertStringContainsString('Do not replace `app(SomeClass::class)` with private static factory helpers that return `new SomeClass()`.', $guideline);
        $this->assertStringContainsString('Code should be easy to test by passing test doubles', $guideline);
        $this->assertStringContainsString('Architecture folder purity:', $guideline);
        $this->assertStringContainsString('Architecture folders MUST stay type-pure.', $guideline);
        $this->assertStringContainsString('`app/Actions/**` contains Actions only.', $guideline);
        $this->assertStringContainsString('`app/Data/**` contains Data Objects, DTOs, and Result objects only.', $guideline);
        $this->assertStringContainsString('$request->toData()', $guideline);
        $this->assertStringNotContainsString('$request->data()', $guideline);
        $this->assertStringContainsString('name: architecture-kit-actions', $skill);
        $this->assertStringContainsString('Action folders MUST contain Actions only.', $skill);
        $this->assertStringContainsString('Do not put Data Objects, Result objects, Enums, Exceptions, API Resources, or Value Objects under `app/Actions/**`.', $skill);
        $this->assertStringContainsString("---\n\n<!-- Generated by Laravel Architecture Kit.", $skill);
        $this->assertStringContainsString('public function toData(): CreateInvoiceData', $formRequestSkill);
        $this->assertStringNotContainsString('public function data(', $formRequestSkill);
        $this->assertStringContainsString('name: architecture-kit-laravel-best-practices', $laravelBestPracticesSkill);
        $this->assertStringContainsString('## Architecture Kit Precedence', $laravelBestPracticesSkill);
        $this->assertStringContainsString('This skill supersedes the generic `laravel-best-practices` skill', $laravelBestPracticesSkill);
        $this->assertFileDoesNotExist($this->tempPath.'/.ai/skills/architecture-kit-value-objects/SKILL.md');
    }

    public function test_laravel_best_practices_is_part_of_default_selection(): void
    {
        $this->assertContains(Architecture::LaravelBestPractices, Architecture::defaultSelection());
        $this->assertSame(Architecture::LaravelBestPractices, array_slice(Architecture::guidelineOrder(), -1)[0]);
        $this->assertArrayHasKey('laravel-best-practices', Architecture::promptOptions());
    }

    public function test_it_warns_when_installing_laravel_best_practices_with_generic_boost_skill_present(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/.ai/skills/laravel-best-practices');
        $files->put($this->tempPath.'/.ai/skills/laravel-best-practices/SKILL.md', "---\nname: laravel-best-practices\n---\n");

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['laravel-best-practices'], Architecture::promptOptions())
            ->expectsOutputToContain('Generic laravel-best-practices skill is present.')
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);
    }

    public function test_it_removes_stale_generated_skills(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Actions]));
        $files->ensureDirectoryExists($this->tempPath.'/.ai/skills/architecture-kit-value-objects');
        $files->put(
            $this->tempPath.'/.ai/skills/architecture-kit-value-objects/SKILL.md',
            "---\nname: architecture-kit-value-objects\n---\n\n<!-- Generated by Laravel Architecture Kit. Do not edit manually. hash=sha256:old -->\n",
        );

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-actions/SKILL.md');
        $this->assertDirectoryDoesNotExist($this->tempPath.'/.ai/skills/architecture-kit-value-objects');
    }

    public function test_it_installs_agent_mcp_and_hooks_in_the_same_preflight(): void
    {
        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'yes')
            ->expectsChoice('Which AI agents should Architecture Kit configure?', ['codex', 'claude_code'], [
                'codex' => 'Codex',
                'claude_code' => 'Claude Code',
            ])
            ->expectsChoice('Which agent integrations should Architecture Kit install?', ['mcp', 'hooks'], [
                'mcp' => 'MCP server config',
                'hooks' => 'Guard hooks',
            ])
            ->expectsOutputToContain('create  resources config/architectures.php')
            ->expectsOutputToContain('create  mcp       .codex/config.toml')
            ->expectsOutputToContain('create  mcp       .mcp.json')
            ->expectsOutputToContain('create  hooks     .codex/hooks.json')
            ->expectsOutputToContain('create  hooks     .claude/settings.json')
            ->expectsOutputToContain('create  state     .architecture-kit/install.json')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $files = new Filesystem;

        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-actions/SKILL.md');
        $this->assertStringContainsString('[mcp_servers.architecture-kit]', $files->get($this->tempPath.'/.codex/config.toml'));
        $this->assertStringContainsString('"architecture-kit:mcp"', $files->get($this->tempPath.'/.mcp.json'));
        $this->assertStringContainsString('.architecture-kit/hooks/guard.sh', $files->get($this->tempPath.'/.codex/hooks.json'));
        $this->assertStringContainsString('.architecture-kit/hooks/guard.sh claude', $files->get($this->tempPath.'/.claude/settings.json'));
        $this->assertStringContainsString('"claude_code"', $files->get($this->tempPath.'/.architecture-kit/install.json'));
    }

    public function test_it_installs_docker_runtime_agent_mcp_and_hooks(): void
    {
        $files = new Filesystem;
        $files->put($this->tempPath.'/compose.yaml', <<<'YAML'
services:
  queue:
    image: php
  api:
    image: php
YAML);

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'docker', $this->runtimeOptions())
            ->expectsChoice('Which Docker Compose service runs PHP?', 'api', [
                'api' => 'api',
                'queue' => 'queue',
            ])
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'yes')
            ->expectsChoice('Which AI agents should Architecture Kit configure?', ['codex'], [
                'codex' => 'Codex',
                'claude_code' => 'Claude Code',
            ])
            ->expectsChoice('Which agent integrations should Architecture Kit install?', ['mcp', 'hooks'], [
                'mcp' => 'MCP server config',
                'hooks' => 'Guard hooks',
            ])
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $config = $files->get($this->tempPath.'/config/architectures.php');
        $codexMcp = $files->get($this->tempPath.'/.codex/config.toml');
        $guard = $files->get($this->tempPath.'/.architecture-kit/hooks/guard.sh');

        $this->assertStringContainsString("'driver' => 'docker'", $config);
        $this->assertStringContainsString("'service' => 'api'", $config);
        $this->assertStringContainsString('command = "docker"', $codexMcp);
        $this->assertStringContainsString('args = ["compose", "exec", "-T", "api", "php", "artisan", "architecture-kit:mcp"]', $codexMcp);
        $this->assertStringContainsString("RUNNER=('docker' 'compose' 'exec' '-T' 'api' 'php')", $guard);
        $this->assertStringContainsString('architecture-kit: runtime unavailable', $guard);
    }

    public function test_install_removes_legacy_agent_runtime_config(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', <<<'PHP'
<?php

use Taqie\ArchitectureKit\Architecture;

return [
    'enabled' => [
        Architecture::Actions,
    ],
    'agents' => [
        'mcp' => [
            'command' => 'docker',
            'args' => [
                'compose',
                'api',
                'php',
                'artisan',
                'architecture-kit:mcp',
            ],
            'cwd' => '/workspace',
        ],
        'hooks' => [
            'commands' => [
                'codex' => 'sh "/repo/.architecture-kit/hooks/guard.sh" codex',
            ],
        ],
    ],
];
PHP);

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions', 'api-resources'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $config = $files->get($this->tempPath.'/config/architectures.php');

        $this->assertStringContainsString('Architecture::Actions', $config);
        $this->assertStringContainsString('Architecture::ApiResources', $config);
        $this->assertStringContainsString("'runtime' => [", $config);
        $this->assertStringContainsString("'driver' => 'local'", $config);
        $this->assertStringNotContainsString("'agents' => [", $config);
        $this->assertStringNotContainsString("'command' => 'docker'", $config);
        $this->assertStringNotContainsString("'architecture-kit:guard'", $config);
    }

    public function test_it_removes_legacy_agent_runtime_config_when_enabled_block_is_compact(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', <<<'PHP'
<?php

use Taqie\ArchitectureKit\Architecture;

return ["enabled" => [Architecture::Actions], "agents" => ["mcp" => ["command" => "docker"]]];
PHP);

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions', 'api-resources'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $config = $files->get($this->tempPath.'/config/architectures.php');

        $this->assertStringContainsString('Architecture::Actions', $config);
        $this->assertStringContainsString('Architecture::ApiResources', $config);
        $this->assertStringNotContainsString('"agents"', $config);
        $this->assertStringContainsString("'runtime' => [", $config);
    }

    public function test_it_generates_resources_for_custom_project_architecture(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/.architecture-kit/architectures/billing-workflows');
        $files->put($this->tempPath.'/.architecture-kit/architectures/billing-workflows/guideline.md', <<<'MARKDOWN'
Billing workflows must keep invoice state transitions inside project-owned use cases.
MARKDOWN);

        $options = array_merge(Architecture::promptOptions(), [
            'billing-workflows' => 'Billing Workflows (custom)',
        ]);

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions', 'billing-workflows'], $options)
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $config = $files->get($this->tempPath.'/config/architectures.php');
        $guideline = $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md');
        $skill = $files->get($this->tempPath.'/.ai/skills/architecture-kit-billing-workflows/SKILL.md');

        $this->assertStringContainsString('Architecture::Actions', $config);
        $this->assertStringContainsString("'billing-workflows'", $config);
        $this->assertStringContainsString('### Billing Workflows', $guideline);
        $this->assertStringContainsString('Billing workflows must keep invoice state transitions inside project-owned use cases.', $guideline);
        $this->assertStringContainsString('name: architecture-kit-billing-workflows', $skill);
    }

    public function test_it_blocks_custom_project_architecture_without_guideline_source(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/.architecture-kit/architectures/billing-workflows');

        $options = array_merge(Architecture::promptOptions(), [
            'billing-workflows' => 'Billing Workflows (custom)',
        ]);

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['billing-workflows'], $options)
            ->expectsOutputToContain('Missing Architecture Kit source resource: '.$this->tempPath.'/.architecture-kit/architectures/billing-workflows/guideline.md')
            ->assertExitCode(1);
    }

    public function test_it_blocks_unmanaged_generated_targets_before_writing_config(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Actions]));
        $files->ensureDirectoryExists($this->tempPath.'/.ai/guidelines');
        $files->put($this->tempPath.'/.ai/guidelines/architecture-kit.md', 'manual guideline');

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsOutputToContain('blocked  .ai/guidelines/architecture-kit.md')
            ->assertExitCode(1);

        $this->assertSame('manual guideline', $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md'));
        $this->assertStringNotContainsString('Architecture::ThinControllers', $files->get($this->tempPath.'/config/architectures.php'));
    }

    public function test_it_blocks_unmanaged_generated_skill_targets_before_writing_config(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Actions]));
        $files->ensureDirectoryExists($this->tempPath.'/.ai/skills/architecture-kit-actions');
        $files->put($this->tempPath.'/.ai/skills/architecture-kit-actions/SKILL.md', 'manual skill');

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsOutputToContain('blocked  .ai/skills/architecture-kit-actions/SKILL.md')
            ->assertExitCode(1);

        $this->assertSame('manual skill', $files->get($this->tempPath.'/.ai/skills/architecture-kit-actions/SKILL.md'));
    }

    public function test_it_requires_at_least_one_architecture(): void
    {
        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', [], Architecture::promptOptions())
            ->assertExitCode(1);
    }

    public function test_it_warns_when_thin_controllers_are_selected_without_actions(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::ThinControllers]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['thin-controllers'], Architecture::promptOptions())
            ->expectsOutputToContain('Thin Controllers were selected without Actions.')
            ->expectsConfirmation('Continue with Thin Controllers without Actions?', 'yes')
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-thin-controllers/SKILL.md');
    }

    public function test_it_warns_when_eloquent_lifecycle_is_selected_without_actions(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::EloquentLifecycle]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['eloquent-lifecycle'], Architecture::promptOptions())
            ->expectsOutputToContain('Eloquent Lifecycle was selected without Actions.')
            ->expectsConfirmation('Continue with Eloquent Lifecycle without Actions?', 'yes')
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-eloquent-lifecycle/SKILL.md');
    }

    public function test_it_generates_eloquent_lifecycle_resources(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Actions, Architecture::EloquentLifecycle]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions', 'eloquent-lifecycle'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $guideline = $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md');
        $skill = $files->get($this->tempPath.'/.ai/skills/architecture-kit-eloquent-lifecycle/SKILL.md');

        $this->assertStringContainsString('### Eloquent Lifecycle', $guideline);
        $this->assertStringContainsString('Before-save observers (`creating`, `saving`, `updating`, `deleting`, `restoring`) are lifecycle adapters only.', $guideline);
        $this->assertStringContainsString('name: architecture-kit-eloquent-lifecycle', $skill);
        $this->assertStringContainsString('Must this behavior run on every save from every origin', $skill);
        $this->assertStringContainsString('Do not put `ShouldHandleEventsAfterCommit` on the whole observer', $skill);
    }

    public function test_it_generates_enum_architecture_resources(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Enums]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['enums'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $guideline = $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md');
        $skill = $files->get($this->tempPath.'/.ai/skills/architecture-kit-enums/SKILL.md');

        $this->assertStringContainsString('### Enums', $guideline);
        $this->assertStringContainsString('Human-facing API Resources MUST expose enums as explicit `value` + `label` objects.', $guideline);
        $this->assertStringContainsString('Rule::enum(InvoiceStatus::class)', $skill);
        $this->assertStringContainsString("'value' => \$this->status->value", $skill);
        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-enums/SKILL.md');
    }

    public function test_it_blocks_modern_php_85_without_php_85_requirement(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::ModernPhp85]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['modern-php-85'], Architecture::promptOptions())
            ->expectsOutputToContain('Modern PHP 8.5 is enabled, but composer.json does not require PHP 8.5 or newer.')
            ->assertExitCode(1);

        $this->assertFileDoesNotExist($this->tempPath.'/.ai/guidelines/architecture-kit.md');
        $this->assertFileDoesNotExist($this->tempPath.'/.ai/skills/architecture-kit-modern-php-85/SKILL.md');
    }

    public function test_it_generates_modern_php_85_resources_when_project_requires_php_85(): void
    {
        $files = new Filesystem;
        $files->put($this->tempPath.'/composer.json', json_encode([
            'require' => [
                'php' => '^8.5',
            ],
        ], JSON_PRETTY_PRINT));
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::ModernPhp85]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['modern-php-85'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $guideline = $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md');
        $skill = $files->get($this->tempPath.'/.ai/skills/architecture-kit-modern-php-85/SKILL.md');

        $this->assertStringContainsString('### Modern PHP 8.5', $guideline);
        $this->assertStringContainsString('do not write legacy-compatible PHP style "just in case"', $skill);
        $this->assertStringContainsString('Use the pipe operator `|>` very carefully', $skill);
        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-modern-php-85/SKILL.md');
    }

    public function test_it_blocks_laravel_ai_without_laravel_ai_requirement(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::LaravelAi]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['laravel-ai'], Architecture::promptOptions())
            ->expectsOutputToContain('Laravel AI is enabled, but composer.json does not require laravel/ai.')
            ->assertExitCode(1);

        $this->assertFileDoesNotExist($this->tempPath.'/.ai/guidelines/architecture-kit.md');
        $this->assertFileDoesNotExist($this->tempPath.'/.ai/skills/architecture-kit-laravel-ai/SKILL.md');
    }

    public function test_it_generates_laravel_ai_resources_when_project_requires_laravel_ai(): void
    {
        $files = new Filesystem;
        $files->put($this->tempPath.'/composer.json', json_encode([
            'require' => [
                'laravel/ai' => '^0.8',
            ],
        ], JSON_PRETTY_PRINT));
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::LaravelAi]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['laravel-ai'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $guideline = $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md');
        $skill = $files->get($this->tempPath.'/.ai/skills/architecture-kit-laravel-ai/SKILL.md');

        $this->assertStringContainsString('### Laravel AI', $guideline);
        $this->assertStringContainsString('Action or Job', $guideline);
        $this->assertStringContainsString('Controllers, FormRequests, API Resources, and Models must not call Laravel AI directly.', $guideline);
        $this->assertStringContainsString('name: architecture-kit-laravel-ai', $skill);
        $this->assertStringContainsString('Generic `runAgent(string $agent, string $input): array` gateways are diagnostic-only', $skill);
        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-laravel-ai/SKILL.md');
    }

    public function test_it_blocks_saloon_without_required_packages(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Saloon]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['saloon'], Architecture::promptOptions())
            ->expectsConfirmation('Continue with Saloon without Actions?', 'yes')
            ->expectsOutputToContain('Saloon is enabled, but composer.json does not satisfy Architecture::Saloon requirements.')
            ->expectsOutputToContain('composer.json is missing or invalid.')
            ->assertExitCode(1);

        $this->assertFileDoesNotExist($this->tempPath.'/.ai/skills/architecture-kit-saloon/SKILL.md');
    }

    public function test_it_blocks_saloon_v3_requirement(): void
    {
        $files = new Filesystem;
        $files->put($this->tempPath.'/composer.json', json_encode([
            'require' => [
                'saloonphp/saloon' => '^3.0',
                'saloonphp/laravel-plugin' => '^3.0',
                'saloonphp/rate-limit-plugin' => '^3.0',
            ],
        ], JSON_PRETTY_PRINT));
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Saloon]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['saloon'], Architecture::promptOptions())
            ->expectsConfirmation('Continue with Saloon without Actions?', 'yes')
            ->expectsOutputToContain('saloonphp/saloon must require ^4.0 and must not allow Saloon 3')
            ->assertExitCode(1);
    }

    public function test_it_generates_saloon_resources_when_required_packages_are_installed(): void
    {
        $files = new Filesystem;
        $files->put($this->tempPath.'/composer.json', json_encode([
            'require' => [
                'saloonphp/saloon' => '^4.0',
                'saloonphp/laravel-plugin' => '^4.0',
                'saloonphp/rate-limit-plugin' => '^4.0',
            ],
        ], JSON_PRETTY_PRINT));
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Actions, Architecture::Saloon]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions', 'saloon'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $guideline = $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md');
        $skill = $files->get($this->tempPath.'/.ai/skills/architecture-kit-saloon/SKILL.md');

        $this->assertStringContainsString('### Saloon', $guideline);
        $this->assertStringContainsString('Every third-party or internal outbound HTTP integration goes through Saloon.', $guideline);
        $this->assertStringContainsString('name: architecture-kit-saloon', $skill);
        $this->assertStringContainsString('MockClient', $skill);
        $this->assertStringContainsString('HasRateLimits', $skill);
    }

    public function test_it_warns_when_saloon_is_selected_without_actions(): void
    {
        $files = new Filesystem;
        $files->put($this->tempPath.'/composer.json', json_encode([
            'require' => [
                'saloonphp/saloon' => '^4.0',
                'saloonphp/laravel-plugin' => '^4.0',
                'saloonphp/rate-limit-plugin' => '^4.0',
            ],
        ], JSON_PRETTY_PRINT));
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Saloon]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['saloon'], Architecture::promptOptions())
            ->expectsOutputToContain('Saloon was selected without Actions.')
            ->expectsConfirmation('Continue with Saloon without Actions?', 'yes')
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);
    }

    public function test_it_generates_services_architecture_resources(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Services]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['services'], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $guideline = $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md');
        $skill = $files->get($this->tempPath.'/.ai/skills/architecture-kit-services/SKILL.md');

        $this->assertStringContainsString('### Services', $guideline);
        $this->assertStringContainsString('Services are allowed only when `Architecture::Services` is enabled.', $guideline);
        $this->assertStringContainsString('name: architecture-kit-services', $skill);
        $this->assertStringContainsString('When `Actions` and `Services` are both enabled, new named write use cases should default to Actions.', $skill);
        $this->assertStringContainsString('final readonly class DocumentPseudonymizationService', $skill);
        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-services/SKILL.md');
    }

    public function test_it_preselects_services_on_first_install_when_project_already_has_services(): void
    {
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->tempPath.'/app/Services/Documents');
        $files->put($this->tempPath.'/app/Services/Documents/DocumentPseudonymizationService.php', <<<'PHP'
<?php

declare(strict_types=1);

namespace App\Services\Documents;

final readonly class DocumentPseudonymizationService
{
}
PHP);

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', [
                'thin-controllers',
                'form-requests',
                'actions',
                'data-objects',
                'api-resources',
                'laravel-best-practices',
                'services',
            ], Architecture::promptOptions())
            ->expectsChoice('How does this project run PHP?', 'local', $this->runtimeOptions())
            ->expectsConfirmation('Install Architecture Kit MCP and hooks for AI agents now?', 'no')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $config = $files->get($this->tempPath.'/config/architectures.php');

        $this->assertStringContainsString('Architecture::Services', $config);
    }

    public function test_fragment_sources_generate_enabled_variants_for_guidelines_and_skills(): void
    {
        $resources = new ArchitectureResources($this->fixturePackagePath(), $this->tempPath);

        $defaultGuideline = $resources->guideline([Architecture::Actions])->contents;
        $defaultSkill = $resources->skills([Architecture::Actions])['actions']->contents;
        $saloonGuideline = $resources->guideline([Architecture::Actions, Architecture::Saloon])->contents;
        $saloonSkill = $resources->skills([Architecture::Actions, Architecture::Saloon])['actions']->contents;

        $this->assertStringContainsString('Actions fragment intro.', $defaultGuideline);
        $this->assertStringContainsString('Default HTTP guidance.', $defaultGuideline);
        $this->assertStringNotContainsString('Saloon HTTP guidance.', $defaultGuideline);
        $this->assertStringContainsString('Default skill body.', $defaultSkill);

        $this->assertStringContainsString('Saloon HTTP guidance.', $saloonGuideline);
        $this->assertStringNotContainsString('Default HTTP guidance.', $saloonGuideline);
        $this->assertStringContainsString('Saloon skill body.', $saloonSkill);
    }

    public function test_laravel_best_practices_renders_conditional_sections(): void
    {
        $resources = new ArchitectureResources(dirname(__DIR__, 2), $this->tempPath);

        $defaultSkill = $resources->skills([Architecture::LaravelBestPractices])['laravel-best-practices']->contents;
        $saloonSkill = $resources->skills([
            Architecture::Actions,
            Architecture::Saloon,
            Architecture::LaravelBestPractices,
        ])['laravel-best-practices']->contents;
        $formRequestGuideline = $resources->guideline([
            Architecture::FormRequests,
            Architecture::LaravelBestPractices,
        ])->contents;

        $this->assertStringContainsString("Use Laravel's `Http` facade", $defaultSkill);
        $this->assertStringContainsString('All outbound HTTP integrations MUST go through Saloon connectors and requests.', $saloonSkill);
        $this->assertStringNotContainsString("Use Laravel's `Http` facade", $saloonSkill);
        $this->assertStringContainsString('All non-trivial HTTP validation MUST use Form Requests.', $formRequestGuideline);
        $this->assertStringContainsString('Do not introduce Services, Repositories, or other patterns unless they are enabled', $defaultSkill);
    }

    public function test_doctor_reports_outdated_generated_resources_when_enabled_set_changes_fragment_variant(): void
    {
        $files = new Filesystem;
        $config = new ArchitectureConfig($this->tempPath.'/config/architectures.php', $files);
        $resources = new ArchitectureResources($this->fixturePackagePath(), $this->tempPath, $files);

        $config->write([Architecture::Actions]);
        $this->writeGenerated($files, [
            $resources->guideline([Architecture::Actions]),
            ...array_values($resources->skills([Architecture::Actions])),
        ]);

        $current = (new ArchitectureDoctor($config, $resources, $files, $this->tempPath, null))->run();
        $this->assertTrue($current->ok());

        $config->write([Architecture::Actions, Architecture::Saloon]);

        $outdated = (new ArchitectureDoctor($config, $resources, $files, $this->tempPath, null))->run();
        $this->assertFalse($outdated->ok());
        $this->assertTrue(collect($outdated->checks)->contains(
            fn ($check): bool => $check->area === 'generated'
                && $check->status === 'outdated'
                && $check->path === '.ai/guidelines/architecture-kit.md',
        ));
    }

    public function test_skill_fragment_directory_must_start_with_frontmatter(): void
    {
        $files = new Filesystem;
        $packagePath = $this->tempPath.'/fixture-package';
        $files->ensureDirectoryExists($packagePath.'/resources/architectures/actions/skill');
        $files->put($packagePath.'/resources/architectures/actions/guideline.md', 'Actions guideline.');
        $files->put($packagePath.'/resources/architectures/actions/skill/10-body.md', '# Missing frontmatter');

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('must start with a frontmatter fragment');

        (new ArchitectureResources($packagePath, $this->tempPath, $files))->skills([Architecture::Actions]);
    }

    public function test_single_file_sources_still_generate_existing_architectures(): void
    {
        $resources = new ArchitectureResources(dirname(__DIR__, 2), $this->tempPath);
        $skill = $resources->skills([Architecture::Actions])['actions']->contents;

        $this->assertStringEndsWith('/resources/architectures/actions/guideline.md', $resources->guidelineSource(Architecture::Actions));
        $this->assertStringEndsWith('/resources/architectures/actions/SKILL.md', $resources->skillSource(Architecture::Actions));
        $this->assertStringContainsString('name: architecture-kit-actions', $skill);
        $this->assertStringContainsString('# Actions', $skill);
        $this->assertStringContainsString('Use this skill when implementing or refactoring write/application use cases.', $skill);
    }

    /**
     * @param  array<int, Architecture>  $architectures
     */
    private function configFor(array $architectures): string
    {
        $lines = [
            '<?php',
            '',
            'use Taqie\\ArchitectureKit\\Architecture;',
            '',
            'return [',
            "    'enabled' => [",
        ];

        foreach ($architectures as $architecture) {
            $lines[] = '        Architecture::'.$architecture->name.',';
        }

        $lines[] = '    ],';
        $lines[] = '];';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function fixturePackagePath(): string
    {
        return __DIR__.'/../Fixtures/fragment-sources';
    }

    /**
     * @return array<string, string>
     */
    private function runtimeOptions(): array
    {
        return [
            'docker' => 'Docker Compose',
            'sail' => 'Laravel Sail',
            'local' => 'Local PHP',
            'custom' => 'Custom command',
        ];
    }

    /**
     * @param  array<int, GeneratedFile>  $generated
     */
    private function writeGenerated(Filesystem $files, array $generated): void
    {
        foreach ($generated as $file) {
            $files->ensureDirectoryExists(dirname($file->path));
            $files->put($file->path, $file->contents);
        }
    }
}
