<?php

declare(strict_types=1);

namespace Taqie\ArchitectureKit\Tests\Feature;

use Illuminate\Filesystem\Filesystem;
use Taqie\ArchitectureKit\Tests\TestCase;

class InstallHooksCommandTest extends TestCase
{
    public function test_it_generates_codex_and_claude_hooks(): void
    {
        $this->artisan('architecture-kit:install-hooks --codex --claude')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $files = new Filesystem();

        $guard = $files->get($this->tempPath.'/.architecture-kit/hooks/guard.sh');
        $codex = $files->get($this->tempPath.'/.codex/hooks.json');
        $claude = $files->get($this->tempPath.'/.claude/settings.json');

        $this->assertStringContainsString('Generated by Laravel Architecture Kit', $guard);
        $this->assertStringContainsString('architecture-kit:guard --changed --strict --json', $guard);
        $this->assertStringContainsString('"Stop"', $codex);
        $this->assertStringContainsString('.architecture-kit/hooks/guard.sh', $codex);
        $this->assertStringContainsString('"Stop"', $claude);
        $this->assertStringContainsString('.architecture-kit/hooks/guard.sh claude', $claude);
        $this->assertSame('755', substr(sprintf('%o', fileperms($this->tempPath.'/.architecture-kit/hooks/guard.sh')), -3));
    }

    public function test_it_is_idempotent_for_generated_hooks(): void
    {
        $this->artisan('architecture-kit:install-hooks --codex')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $this->artisan('architecture-kit:install-hooks --codex')
            ->expectsOutputToContain('No agent integration changes needed.')
            ->assertExitCode(0);
    }

    public function test_it_blocks_unmanaged_hook_config(): void
    {
        $files = new Filesystem();
        $files->ensureDirectoryExists($this->tempPath.'/.codex');
        $files->put($this->tempPath.'/.codex/hooks.json', '{not json');

        $this->artisan('architecture-kit:install-hooks --codex')
            ->expectsOutputToContain('blocked  .codex/hooks.json')
            ->assertExitCode(1);

        $this->assertSame('{not json', $files->get($this->tempPath.'/.codex/hooks.json'));
    }

    public function test_it_merges_existing_hook_config(): void
    {
        $files = new Filesystem();
        $files->ensureDirectoryExists($this->tempPath.'/.codex');
        $files->put($this->tempPath.'/.codex/hooks.json', json_encode([
            'hooks' => [
                'Stop' => [
                    [
                        'hooks' => [
                            [
                                'type' => 'command',
                                'command' => 'vendor/bin/phpunit',
                            ],
                        ],
                    ],
                ],
            ],
        ], JSON_PRETTY_PRINT));

        $this->artisan('architecture-kit:install-hooks --codex')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $contents = $files->get($this->tempPath.'/.codex/hooks.json');

        $this->assertStringContainsString('vendor/bin/phpunit', $contents);
        $this->assertStringContainsString('.architecture-kit/hooks/guard.sh', $contents);
    }
}
