<?php

declare(strict_types=1);

namespace Taqie\ArchitectureKit\Tests\Feature;

use Illuminate\Filesystem\Filesystem;
use Taqie\ArchitectureKit\Architecture;
use Taqie\ArchitectureKit\Tests\TestCase;

class InstallCommandTest extends TestCase
{
    public function test_it_generates_config_guideline_and_selected_skills(): void
    {
        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', [
                'thin-controllers',
                'form-requests',
                'actions',
                'data-objects',
                'api-resources',
            ], Architecture::promptOptions())
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $files = new Filesystem();

        $config = $files->get($this->tempPath.'/config/architectures.php');
        $guideline = $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md');
        $skill = $files->get($this->tempPath.'/.ai/skills/architecture-kit-actions/SKILL.md');

        $this->assertStringContainsString('Architecture::ThinControllers', $config);
        $this->assertStringContainsString('Architecture::Actions', $config);
        $this->assertStringContainsString('Generated by Laravel Architecture Kit', $guideline);
        $this->assertStringContainsString('### Actions', $guideline);
        $this->assertStringContainsString('Write flow:', $guideline);
        $this->assertStringContainsString('name: architecture-kit-actions', $skill);
        $this->assertStringContainsString("---\n\n<!-- Generated by Laravel Architecture Kit.", $skill);
        $this->assertFileDoesNotExist($this->tempPath.'/.ai/skills/architecture-kit-value-objects/SKILL.md');
    }

    public function test_it_removes_stale_generated_skills(): void
    {
        $files = new Filesystem();
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Actions]));
        $files->ensureDirectoryExists($this->tempPath.'/.ai/skills/architecture-kit-value-objects');
        $files->put(
            $this->tempPath.'/.ai/skills/architecture-kit-value-objects/SKILL.md',
            "---\nname: architecture-kit-value-objects\n---\n\n<!-- Generated by Laravel Architecture Kit. Do not edit manually. hash=sha256:old -->\n",
        );

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions'], Architecture::promptOptions())
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-actions/SKILL.md');
        $this->assertDirectoryDoesNotExist($this->tempPath.'/.ai/skills/architecture-kit-value-objects');
    }

    public function test_it_blocks_unmanaged_generated_targets_before_writing_config(): void
    {
        $files = new Filesystem();
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Actions]));
        $files->ensureDirectoryExists($this->tempPath.'/.ai/guidelines');
        $files->put($this->tempPath.'/.ai/guidelines/architecture-kit.md', 'manual guideline');

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions'], Architecture::promptOptions())
            ->expectsOutputToContain('blocked  .ai/guidelines/architecture-kit.md')
            ->assertExitCode(1);

        $this->assertSame('manual guideline', $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md'));
        $this->assertStringNotContainsString('Architecture::ThinControllers', $files->get($this->tempPath.'/config/architectures.php'));
    }

    public function test_it_blocks_unmanaged_generated_skill_targets_before_writing_config(): void
    {
        $files = new Filesystem();
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Actions]));
        $files->ensureDirectoryExists($this->tempPath.'/.ai/skills/architecture-kit-actions');
        $files->put($this->tempPath.'/.ai/skills/architecture-kit-actions/SKILL.md', 'manual skill');

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['actions'], Architecture::promptOptions())
            ->expectsOutputToContain('blocked  .ai/skills/architecture-kit-actions/SKILL.md')
            ->assertExitCode(1);

        $this->assertSame('manual skill', $files->get($this->tempPath.'/.ai/skills/architecture-kit-actions/SKILL.md'));
    }

    public function test_it_requires_at_least_one_architecture(): void
    {
        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', [], Architecture::promptOptions())
            ->assertExitCode(1);
    }

    public function test_it_warns_when_thin_controllers_are_selected_without_actions(): void
    {
        $files = new Filesystem();
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::ThinControllers]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['thin-controllers'], Architecture::promptOptions())
            ->expectsOutputToContain('Thin Controllers were selected without Actions.')
            ->expectsConfirmation('Continue with Thin Controllers without Actions?', 'yes')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-thin-controllers/SKILL.md');
    }

    public function test_it_generates_enum_architecture_resources(): void
    {
        $files = new Filesystem();
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::Enums]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['enums'], Architecture::promptOptions())
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $guideline = $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md');

        $this->assertStringContainsString('### Enums', $guideline);
        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-enums/SKILL.md');
    }

    public function test_it_warns_when_modern_php_85_is_selected_without_php_85_requirement(): void
    {
        $files = new Filesystem();
        $files->ensureDirectoryExists($this->tempPath.'/config');
        $files->put($this->tempPath.'/config/architectures.php', $this->configFor([Architecture::ModernPhp85]));

        $this->artisan('architecture-kit:install')
            ->expectsChoice('Which architecture patterns does this project use?', ['modern-php-85'], Architecture::promptOptions())
            ->expectsOutputToContain('Modern PHP 8.5 was selected, but composer.json does not require PHP 8.5.')
            ->expectsConfirmation('Continue with Modern PHP 8.5 guidance anyway?', 'yes')
            ->expectsConfirmation('Continue?', 'yes')
            ->assertExitCode(0);

        $guideline = $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md');

        $this->assertStringContainsString('### Modern PHP 8.5', $guideline);
        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-modern-php-85/SKILL.md');
    }

    /**
     * @param  array<int, Architecture>  $architectures
     */
    private function configFor(array $architectures): string
    {
        $lines = [
            '<?php',
            '',
            'use Taqie\\ArchitectureKit\\Architecture;',
            '',
            'return [',
            "    'enabled' => [",
        ];

        foreach ($architectures as $architecture) {
            $lines[] = '        Architecture::'.$architecture->name.',';
        }

        $lines[] = '    ],';
        $lines[] = '];';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
