<?php

declare(strict_types=1);

namespace GracjanKubicki\ArchitectureKit\Tests\Feature;

use GracjanKubicki\ArchitectureKit\Architecture;
use GracjanKubicki\ArchitectureKit\Config\ArchitectureConfig;
use GracjanKubicki\ArchitectureKit\Install\Requirements\LaravelAiRequirement;
use GracjanKubicki\ArchitectureKit\Resources\ArchitectureResources;
use GracjanKubicki\ArchitectureKit\Tests\TestCase;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Facades\Artisan;

final class SyncCommandTest extends TestCase
{
    public function test_it_regenerates_managed_resources_without_changing_selection_or_unmanaged_files(): void
    {
        $files = new Filesystem;
        $config = new ArchitectureConfig($this->tempPath.'/config/architectures.php', $files);
        $config->write([Architecture::Actions]);
        $files->ensureDirectoryExists($this->tempPath.'/.ai/guidelines');
        $files->put($this->tempPath.'/.ai/guidelines/architecture-kit.md', '<!-- Generated by Laravel Architecture Kit. Do not edit manually. hash=sha256:old -->');
        $files->ensureDirectoryExists($this->tempPath.'/.ai/skills/architecture-kit-value-objects');
        $files->put($this->tempPath.'/.ai/skills/architecture-kit-value-objects/SKILL.md', "---\nname: architecture-kit-value-objects\n---\n\n<!-- Generated by Laravel Architecture Kit. Do not edit manually. hash=sha256:old -->\n");
        $files->ensureDirectoryExists($this->tempPath.'/.ai/skills/custom-project-skill');
        $files->put($this->tempPath.'/.ai/skills/custom-project-skill/SKILL.md', 'keep me');
        $configBefore = $files->get($this->tempPath.'/config/architectures.php');

        $this->artisan('architecture-kit:sync --no-interaction')
            ->expectsOutputToContain('Architecture Kit resources synchronized.')
            ->assertExitCode(0);

        $this->assertSame($configBefore, $files->get($this->tempPath.'/config/architectures.php'));
        $this->assertFileExists($this->tempPath.'/.ai/skills/architecture-kit-actions/SKILL.md');
        $this->assertDirectoryDoesNotExist($this->tempPath.'/.ai/skills/architecture-kit-value-objects');
        $this->assertSame('keep me', $files->get($this->tempPath.'/.ai/skills/custom-project-skill/SKILL.md'));
    }

    public function test_dry_run_reports_the_plan_without_writing(): void
    {
        (new ArchitectureConfig($this->tempPath.'/config/architectures.php'))->write([Architecture::Actions]);

        $exit = Artisan::call('architecture-kit:sync', ['--dry-run' => true, '--agent' => true]);
        $payload = json_decode(trim(Artisan::output()), true);

        $this->assertSame(0, $exit);
        $this->assertTrue($payload['ok']);
        $this->assertTrue($payload['dry_run']);
        $this->assertNotEmpty($payload['changes']['create']);
        $this->assertFileDoesNotExist($this->tempPath.'/.ai/guidelines/architecture-kit.md');
    }

    public function test_it_blocks_before_writes_when_laravel_ai_is_incompatible(): void
    {
        $files = new Filesystem;
        $files->put($this->tempPath.'/composer.json', json_encode([
            'require' => [
                'gracjankubicki/laravel-architecture-kit' => '^0.2',
                'laravel/ai' => '^0.10',
            ],
        ], JSON_THROW_ON_ERROR));
        (new ArchitectureConfig($this->tempPath.'/config/architectures.php', $files))->write([Architecture::LaravelAi]);
        $files->ensureDirectoryExists($this->tempPath.'/.ai/guidelines');
        $files->put($this->tempPath.'/.ai/guidelines/architecture-kit.md', 'previous managed state');

        $this->artisan('architecture-kit:sync --no-interaction')
            ->expectsOutputToContain('permits unsupported versions')
            ->assertExitCode(1);

        $this->assertSame('previous managed state', $files->get($this->tempPath.'/.ai/guidelines/architecture-kit.md'));
    }

    public function test_it_upgrades_generated_resources_from_profile_08_to_09(): void
    {
        $files = new Filesystem;
        $this->writeLaravelAiFixture('^0.8', '0.8.1');
        $config = new ArchitectureConfig($this->tempPath.'/config/architectures.php', $files);
        $config->write([Architecture::LaravelAi]);
        $compatibility = LaravelAiRequirement::resolve($files, $this->tempPath);
        $resources = new ArchitectureResources(dirname(__DIR__, 2), $this->tempPath, $files, laravelAi: $compatibility);
        $skill = $resources->skills([Architecture::LaravelAi])['laravel-ai'];
        $guideline = $resources->guideline([Architecture::LaravelAi]);
        $files->ensureDirectoryExists(dirname($skill->path));
        $files->put($skill->path, $skill->contents);
        $files->ensureDirectoryExists(dirname($guideline->path));
        $files->put($guideline->path, $guideline->contents);

        $this->writeLaravelAiFixture('^0.9', '0.9.0');

        $this->artisan('architecture-kit:doctor')
            ->expectsOutputToContain('profile    laravel-ai@0.9')
            ->expectsOutputToContain('outdated .ai/skills/architecture-kit-laravel-ai/SKILL.md')
            ->assertExitCode(1);

        $this->artisan('architecture-kit:sync --no-interaction')->assertExitCode(0);

        $updated = $files->get($this->tempPath.'/.ai/skills/architecture-kit-laravel-ai/SKILL.md');
        $this->assertStringContainsString('Profile: `laravel-ai@0.9`', $updated);
        $this->assertStringContainsString('withProviderOptions(', $updated);
        $this->assertStringNotContainsString('laravel-ai@0.8', $updated);
    }

    private function writeLaravelAiFixture(string $constraint, string $version): void
    {
        $files = new Filesystem;
        $files->put($this->tempPath.'/composer.json', json_encode([
            'require' => [
                'gracjankubicki/laravel-architecture-kit' => '^0.2',
                'laravel/ai' => $constraint,
            ],
        ], JSON_THROW_ON_ERROR));
        $files->put($this->tempPath.'/composer.lock', json_encode([
            'packages' => [['name' => 'laravel/ai', 'version' => $version]],
            'packages-dev' => [],
        ], JSON_THROW_ON_ERROR));
        $files->ensureDirectoryExists($this->tempPath.'/vendor/composer');
        $files->put($this->tempPath.'/vendor/composer/installed.php', "<?php\nreturn ['versions' => ['laravel/ai' => ['pretty_version' => '{$version}']]];\n");
        $files->ensureDirectoryExists($this->tempPath.'/vendor/laravel/ai/src/Responses');
        $files->put($this->tempPath.'/vendor/laravel/ai/src/Responses/StructuredAgentResponse.php', '<?php class StructuredAgentResponse implements ArrayAccess { public function toArray(): array {} }');
        $files->ensureDirectoryExists($this->tempPath.'/vendor/laravel/ai/src/Concerns');
        $files->put($this->tempPath.'/vendor/laravel/ai/src/Concerns/ProviderOptions.php', '<?php trait ProviderOptions { public function withProviderOptions(array $options): static {} }');
    }
}
