<?php

declare(strict_types=1);

namespace GracjanKubicki\ArchitectureKit\Tests\Unit;

use GracjanKubicki\ArchitectureKit\Resources\UpgradeGuideResources;
use Illuminate\Filesystem\Filesystem;
use PHPUnit\Framework\TestCase;
use RuntimeException;

final class UpgradeGuideResourcesTest extends TestCase
{
    private string $packagePath;

    private string $projectPath;

    protected function setUp(): void
    {
        parent::setUp();

        $root = sys_get_temp_dir().'/architecture-kit-upgrades-'.uniqid('', true);
        $this->packagePath = $root.'/package';
        $this->projectPath = $root.'/project';
        $files = new Filesystem;
        $files->ensureDirectoryExists($this->packagePath);
        $files->ensureDirectoryExists($this->projectPath);
    }

    protected function tearDown(): void
    {
        (new Filesystem)->deleteDirectory(dirname($this->packagePath));

        parent::tearDown();
    }

    public function test_it_rejects_duplicate_skill_names_across_versioned_guides(): void
    {
        $this->writeGuide('vendor-package', '1.0', '2.0', 'architecture-kit-upgrade-vendor-package');
        $this->writeGuide('vendor-package', '2.0', '3.0', 'architecture-kit-upgrade-vendor-package');

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Duplicate Architecture Kit upgrade skill name');

        $this->resources()->skills(['vendor-architecture']);
    }

    public function test_a_new_package_transition_is_distributed_without_a_new_php_adapter(): void
    {
        $this->writeGuide(
            'vendor-package',
            '1.0',
            '2.0',
            'architecture-kit-upgrade-vendor-package-1-0-to-2-0',
        );

        $skills = $this->resources()->skills(['vendor-architecture']);
        $skill = $skills['upgrade:vendor-package:1.0-to-2.0'];

        $this->assertSame(
            $this->projectPath.'/.ai/skills/architecture-kit-upgrade-vendor-package-1-0-to-2-0/SKILL.md',
            $skill->path,
        );
        $this->assertStringContainsString('Generated by Laravel Architecture Kit', $skill->contents);
        $this->assertStringContainsString('name: architecture-kit-upgrade-vendor-package-1-0-to-2-0', $skill->contents);
    }

    public function test_it_rejects_package_metadata_that_does_not_match_the_source_path(): void
    {
        $this->writeGuide('different-package', '1.0', '2.0', 'architecture-kit-upgrade-vendor-package');

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('package metadata must match its package directory');

        $this->resources()->skills(['vendor-architecture']);
    }

    public function test_it_rejects_a_transition_that_does_not_move_forward(): void
    {
        $this->writeGuide('vendor-package', '2.0', '1.0', 'architecture-kit-upgrade-vendor-package');

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('target a newer version');

        $this->resources()->skills(['vendor-architecture']);
    }

    public function test_it_rejects_a_skill_without_a_trigger_description(): void
    {
        $this->writeGuide(
            'vendor-package',
            '1.0',
            '2.0',
            'architecture-kit-upgrade-vendor-package',
            '',
        );

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('must define a non-empty description');

        $this->resources()->skills(['vendor-architecture']);
    }

    private function resources(): UpgradeGuideResources
    {
        return new UpgradeGuideResources(
            $this->packagePath,
            $this->projectPath,
            new Filesystem,
        );
    }

    private function writeGuide(
        string $package,
        string $from,
        string $to,
        string $name,
        string $description = 'Upgrade fixture.',
    ): void {
        $path = $this->packagePath."/resources/upgrades/{$package}/{$from}-to-{$to}/SKILL.md";
        $files = new Filesystem;
        $files->ensureDirectoryExists(dirname($path));
        $files->put($path, <<<MARKDOWN
---
name: {$name}
description: "{$description}"
metadata:
  architecture: vendor-architecture
  package: vendor/package
  from: "{$from}"
  to: "{$to}"
---

# Upgrade
MARKDOWN);
    }
}
