<?php

declare(strict_types=1);

namespace Taqie\ArchitectureKit\Install\Hooks;

use Illuminate\Filesystem\Filesystem;
use Taqie\ArchitectureKit\Install\Agents\Agent;
use Taqie\ArchitectureKit\Install\Contracts\SupportsHooks;
use Taqie\ArchitectureKit\Install\InstallResult;

final readonly class HookWriter
{
    private const MARKER = 'Generated by Laravel Architecture Kit. Do not edit manually.';

    public function __construct(
        private Filesystem $files,
        private string $basePath,
    ) {
    }

    /**
     * @param  array<int, Agent&SupportsHooks>  $agents
     */
    public function plan(array $agents): InstallResult
    {
        $creates = [];
        $updates = [];
        $blocked = [];

        foreach ($this->targets($agents) as $path => $contents) {
            if ($contents === null) {
                $blocked[] = $path;

                continue;
            }

            $absolutePath = $this->absolute($path);

            if (! $this->files->exists($absolutePath)) {
                $creates[] = $path;

                continue;
            }

            if ($this->files->get($absolutePath) !== $contents) {
                $updates[] = $path;
            }
        }

        return new InstallResult($creates, $updates, $blocked);
    }

    /**
     * @param  array<int, Agent&SupportsHooks>  $agents
     */
    public function write(array $agents): void
    {
        foreach ($this->targets($agents) as $path => $contents) {
            if ($contents === null) {
                continue;
            }

            $absolutePath = $this->absolute($path);
            $this->files->ensureDirectoryExists(dirname($absolutePath));
            $this->files->put($absolutePath, $contents);

            if ($path === '.architecture-kit/hooks/guard.sh') {
                $this->files->chmod($absolutePath, 0755);
            }
        }
    }

    public function guardScriptCurrent(): bool
    {
        $path = $this->absolute('.architecture-kit/hooks/guard.sh');

        return $this->files->exists($path)
            && $this->files->get($path) === $this->guardScript();
    }

    public function agentHookCurrent(Agent&SupportsHooks $agent): bool
    {
        $rendered = $this->renderHookConfig($agent);
        $path = $this->absolute($agent->hookConfigPath());

        return $rendered !== null
            && $this->files->exists($path)
            && $this->files->get($path) === $rendered;
    }

    /**
     * @param  array<int, Agent&SupportsHooks>  $agents
     * @return array<string, string|null>
     */
    private function targets(array $agents): array
    {
        $targets = [
            '.architecture-kit/hooks/guard.sh' => $this->guardScript(),
            '.architecture-kit/hooks/README.md' => $this->readme(),
        ];

        foreach ($agents as $agent) {
            $targets[$agent->hookConfigPath()] = $this->renderHookConfig($agent);
        }

        return $targets;
    }

    private function renderHookConfig(Agent&SupportsHooks $agent): ?string
    {
        $path = $this->absolute($agent->hookConfigPath());
        $decoded = [];

        if ($this->files->exists($path) && $this->files->size($path) >= 3) {
            $decoded = json_decode($this->files->get($path), true);

            if (! is_array($decoded) || json_last_error() !== JSON_ERROR_NONE) {
                return null;
            }
        }

        $hooks = $decoded['hooks'] ?? [];

        if (! is_array($hooks)) {
            return null;
        }

        $stopGroups = $hooks['Stop'] ?? [];

        if (! is_array($stopGroups)) {
            return null;
        }

        $stopGroups = $this->withoutArchitectureKitHooks($stopGroups);
        $stopGroups[] = [
            'hooks' => [
                [
                    'type' => 'command',
                    'command' => $this->commandFor($agent),
                    'timeout' => 120,
                    'statusMessage' => self::MARKER,
                ],
            ],
        ];

        $hooks['Stop'] = $stopGroups;
        unset($decoded['_architectureKit']);

        if ($agent->hookMode() === 'codex') {
            $decoded = [
                'hooks' => $hooks,
            ];
        } else {
            $decoded['hooks'] = $hooks;
        }

        return (json_encode($decoded, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?: '{}')."\n";
    }

    /**
     * @param  array<int, mixed>  $groups
     * @return array<int, mixed>
     */
    private function withoutArchitectureKitHooks(array $groups): array
    {
        $filtered = [];

        foreach ($groups as $group) {
            if (! is_array($group)) {
                $filtered[] = $group;

                continue;
            }

            $hooks = $group['hooks'] ?? [];

            if (! is_array($hooks)) {
                $filtered[] = $group;

                continue;
            }

            $hooks = array_values(array_filter(
                $hooks,
                fn (mixed $hook): bool => ! $this->isArchitectureKitHook($hook),
            ));

            if ($hooks !== []) {
                $group['hooks'] = $hooks;
                $filtered[] = $group;
            }
        }

        return array_values($filtered);
    }

    private function isArchitectureKitHook(mixed $hook): bool
    {
        if (! is_array($hook)) {
            return false;
        }

        $command = $hook['command'] ?? '';
        $message = $hook['statusMessage'] ?? '';

        return (is_string($command) && str_contains($command, '.architecture-kit/hooks/guard.sh'))
            || (is_string($message) && str_contains($message, 'Laravel Architecture Kit'));
    }

    private function commandFor(Agent&SupportsHooks $agent): string
    {
        $configured = config('architectures.agents.hooks.commands.'.$agent->hookMode());

        if (is_string($configured) && $configured !== '') {
            return $configured;
        }

        if ($agent->hookMode() === 'claude') {
            return (new ClaudeHookWriter())->command();
        }

        return (new CodexHookWriter())->command();
    }

    private function guardScript(): string
    {
        $guardCommand = $this->guardCommand();

        return <<<SH
#!/usr/bin/env bash
# Generated by Laravel Architecture Kit. Do not edit manually.
set -u

MODE="\${1:-codex}"
ROOT="\$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

cd "\$ROOT" || exit 1

OUTPUT="\$($guardCommand 2>&1)"
STATUS=\$?

if [ "\$STATUS" -eq 0 ]; then
    exit 0
fi

printf '%s\\n' "\$OUTPUT" >&2

if [ "\$MODE" = "claude" ]; then
    exit 2
fi

exit "\$STATUS"
SH;
    }

    private function readme(): string
    {
        return <<<'MD'
# Architecture Kit Hooks

Generated by Laravel Architecture Kit. Do not edit manually.

Run `php artisan architecture-kit:install-agents` to repair these files.
MD;
    }

    private function absolute(string $path): string
    {
        return $this->basePath.'/'.$path;
    }

    private function guardCommand(): string
    {
        $configured = config('architectures.agents.hooks.guard_command');

        if (is_string($configured) && $configured !== '') {
            return $configured;
        }

        if (is_array($configured)) {
            $parts = array_values(array_filter($configured, is_string(...)));

            if ($parts !== []) {
                return implode(' ', array_map(escapeshellarg(...), $parts));
            }
        }

        return 'php artisan architecture-kit:guard --changed --strict --json';
    }
}
